language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
- stable
before_install:
- "npm install -g typescript@^2.3"
- "npm install -g npm@^4.6.1"
script:
- npm bootstrap
- npm test
